### PR TITLE
P3D missing on global statement

### PR DESCRIPTION
**Pull request by villares**
Note on line 1105:
`    P3D = p5_instance.WEBGL`

### CODE REVIEW

**Comment by villares** [comment]
Sorry for the awkward commit history, feel free to close this and just add your own clean commit...

**Comment by berinhard** [comment]
@villares no worries about the commit.. But can you add it to [pyodide JS new template file](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/templates/pyodide/target_sketch.js.template#L956) too?

**Review by berinhard — CHANGES_REQUESTED** [review]
@villares no worries about the commit and the commit looks good.. But can you add it to [pyodide JS new template file](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/templates/pyodide/target_sketch.js.template#L956) too?

**Comment by villares** [comment]
> @villares no worries about the commit and the commit looks good.. But can you add it to [pyodide JS new template file](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/templates/pyodide/target_sketch.js.template#L956) too?

Done!I was going to tell you I haven't found the main template and you just provided the link! <3

**Review by berinhard — APPROVED** [review]
Thanks a lot @villares!

**Pull request merged**
