### PR TITLE
Adding PVector alias to createVector() and p5.Vector class method aliases

### PR DESCRIPTION
**Pull request by villares**
This should make more examples from Processing Python mode run with less modification
as well as mirror part of the PR adding PVector wrapper functionality for the pyp5js pyodide mode (minus the operator overloading).

### CODE REVIEW

**Comment by GoToLoop** [comment]
I guess it'd be nice following the approach already used on the module below:
https://github.com/berinhard/pyp5js/blob/develop/pyp5js/python_functions.py

`PVector.dist = p5.Vector.dist` ---> `setattr(PVector, 'dist', p5.Vector.dist)`

**Comment by villares** [comment]
Oh! Thank you for the careful explanation @GoToLoop, I didn't get it the first time Bernardo showed it. I'm not used to using `setattr()` I will try that!

**Comment by berinhard** [comment]
Hey @villares this looks great to me! Do you have a ready sketch code I could use to test and, so, merge this PR?

**Comment by villares** [comment]
> Hey @villares this looks great to me! Do you have a ready sketch code I could use to test and, so, merge this PR?

For the Pyodide mode (with operator overloading) "the JDF tests" are here: https://gist.github.com/villares/e639a34eef756beba2f79a55203cd51e

For the Transcrypt mode I think this should pass:

```
from pyp5js import *

def setup():
    createCanvas(600, 200)
    background(160)

def draw():
    fill("blue")
    background(200)
    radius = sin(frameCount / 60) * 50 + 50
    ellipse(100,100, radius, radius)    
    v = p5.Vector.fromAngle(0)
    text(v, 100, 100)
```

Or this:

```
def setup():
    createCanvas(400, 400)
    background(160)

def draw():
    translate(50, 200)
    fill("blue")
    background(200)
    radius = sin(frameCount / 60) * 50 + 50
    v = PVector(50, 50)
    ellipse(v.x, v.y, radius, radius)
    v.div(2)
    ellipse(v.x, v.y, radius, radius)
    v.add(30, 30)
    ellipse(v.x, v.y, radius, radius)
    w = PVector.add(v, PVector(50,0))
    ellipse(w.x, w.y, radius, radius)
    z = PVector.div(w, 2)
    ellipse(z.x, z.y, radius, radius)
    # some tests
    r = PVector.fromAngles(0)  # ANNGULOS DIFERENTES!
    r.setMag(10)
    assert r.x == -10 and r.y == 0 and r.z == 0
    text(r.toString(), 100, 20)
    # Other p5js methods
    r.setMag(100)
    assert r.mag() == 100
    r.normalize()
    assert r.mag() == 1
    r.limit(10)
    assert r.mag() == 1
    r.limit(0.1)
    assert r.mag() == 0.1 and r.heading() == 0
    r.rotate(PI)
    assert r.heading() == PI
```

**Comment by berinhard** [comment]
It's working! This is great!

**Pull request merged**
