### PR TITLE
Added all p5.js constants found in contants.js

### PR DESCRIPTION
**Pull request by villares**
Harvested from https://github.com/processing/p5.js/blob/master/src/core/constants.js
Should fix issue #36
Note: the previously existing constants are still there, but in alphabetical order.

### CODE REVIEW

**Comment by berinhard** [comment]
Thank you so much @villares. If I'm not asking to much, could you update the `pytop5js.py` file and add it to this PR as well? To do so, you just have to run:

```
$ python pyp5js/update_pytop5js.py
```

This will automatically update the file by adding the new constants.

**Comment by villares** [comment]
Hmmm. I'll see if I can do it tomorrow. I Couldn't find my local copy of pyp5js to replace the .yml

**Comment by berinhard** [comment]
@villares maybe you're using an older version of pyp5js. I've released 0.0.4.1 last weekend and I merged the yaml files in this version.

**Comment by berinhard** [comment]
@villares maybe this command can help you:

```
$ sudo find / -name "p5_reference.yml" -type f
```

**Comment by villares** [comment]
I hope this is correct! :D 

Unable to run `$ python3 pyp5js/update_pytop5js.py` in my system, I had to navigate my terminal into the package folder and sudo it into submission...

**Pull request merged**
